spring.application.name=Back
spring.datasource.url=jdbc:mysql://localhost:4444/backAWS?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8089
